(() => {
'use strict';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d'),mc=$('map').getContext('2d');
ctx.imageSmoothingEnabled=false;
const W=960,H=640,TAU=Math.PI*2,keys=new Set();
let mode='title', rooms=[],room,player,particles=[],shots=[],drops=[],boomerang=null,time=0,last=0,shake=0,toastTime=0,runSeed=0,kills=0,clears=0,transition=0;
let legacy={deaths:0,wins:0};try{legacy=JSON.parse(localStorage.getItem('forest-echoes')||'null')||legacy;}catch{}
const rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const relics=[{id:'blade',icon:'⚔',name:'Éclat de puissance',desc:'+1 dégât à l’épée',apply:p=>p.damage++},{id:'heart',icon:'♥',name:'Cœur de la forêt',desc:'+1 cœur et soin complet',apply:p=>{p.max++;p.hp=p.max;}},{id:'boots',icon:'»',name:'Bottes du vent',desc:'+20 % de vitesse',apply:p=>p.speed*=1.2},{id:'ring',icon:'✦',name:'Anneau de braise',desc:'L’épée brûle les ennemis',apply:p=>p.fire=true},{id:'boom',icon:'⌁',name:'Croissant ancestral',desc:'Boomerang : dégâts doublés',apply:p=>p.boomDamage+=2},{id:'charm',icon:'❋',name:'Larme de fée',desc:'Récupérez 1 cœur par salle gagnée',apply:p=>p.regen=true}];
const layout=[[0,0,'start','Le seuil du sanctuaire'],[0,-1,'fight','Le cloître des fougères'],[-1,-1,'fight','Les pierres murmurantes'],[-2,-1,'treasure','La chambre des offrandes'],[1,-1,'fight','La galerie des lucioles'],[2,-1,'shop','Le refuge du colporteur'],[0,-2,'fight','Le jardin des épines'],[-1,-2,'fight','La crypte verte'],[-2,-2,'key','L’autel de la petite lune'],[1,-2,'fight','Le passage des sentinelles'],[1,-3,'ante','Le dernier souffle'],[2,-3,'boss','Le cœur des racines']];
const soundtrack = new ForestAudio();
function sfx(name){soundtrack.play(name);}
function syncSoundButton(){ $('sound').textContent='SON : '+(soundtrack.enabled?'ON':'OFF'); $('sound').title=soundtrack.enabled?'Couper musique et bruitages':'Activer musique et bruitages'; }
syncSoundButton();
function toast(text){$('toast').textContent=text;$('toast').style.opacity=1;toastTime=3;}
function persist(){try{localStorage.setItem('forest-echoes',JSON.stringify(legacy));}catch{}}
function newRun(){soundtrack.setPaused(false);soundtrack.unlock();runSeed=Math.random()*99999;time=0;kills=0;clears=0;keys.clear();player={x:480,y:410,hp:5,max:5,money:Math.min(8,(legacy.deaths+legacy.wins)*2),key:0,damage:1,boomDamage:2,speed:205,dir:-Math.PI/2,inv:0,attack:0,attackCD:0,dash:0,dashCD:0,boomCD:0,items:[],fire:false,regen:false};rooms=layout.map(([x,y,type,name],i)=>({x,y,type,name,id:i,visited:false,clear:['start','treasure','shop','ante'].includes(type),enemies:null,objects:[],opened:false,seed:Math.random()*1000,offer:[...relics].sort(()=>Math.random()-.5).slice(0,3)}));enter(rooms[0]);mode='play';$('overlay').classList.add('hidden');canvas.focus();updateHUD();toast('Trouvez la clé de lune et le gardien. Bonne aventure !');}
function neighbor(dx,dy){return rooms.find(r=>r.x===room.x+dx&&r.y===room.y+dy);}
function enemy(type,x,y){return{x,y,type,hp:type==='boss'?54:type==='knight'?6:3,max:type==='boss'?54:type==='knight'?6:3,t:rand(0,2),cool:type==='boss'?2.4:rand(.6,1.8),windup:0,recover:0,pattern:0,aim:0,hit:0,burn:0,phase:0,charge:0,vx:0,vy:0};}
function enter(r,from){room=r;r.visited=true;shots=[];particles=[];drops=r.drops||[];boomerang=null;transition=.4;player.inv=Math.max(player.inv,.65);if(!r.enemies){r.enemies=[];if(!r.clear){if(r.type==='boss'){r.enemies=[enemy('boss',480,240)];toast('MORNE-RACINE · Esquivez la charge, puis frappez !');sfx('boss');}else{const n=r.type==='key'?5:3+Math.floor(Math.random()*2);for(let i=0;i<n;i++){const positions=[[235,190],[715,190],[250,440],[710,440],[480,270]];r.enemies.push(enemy(['slime','bat','spitter','knight'][Math.floor(Math.random()* (r.id>5?4:3))],...positions[i]));}}if(!['start','boss','shop','treasure','ante'].includes(r.type))r.objects=[{x:320,y:256,w:48,h:48},{x:592,y:352,w:48,h:48}];}
}
if(from==='left'){player.x=80;player.y=320;}if(from==='right'){player.x=880;player.y=320;}if(from==='top'){player.x=480;player.y=82;}if(from==='bottom'){player.x=480;player.y=558;}
if(from)sfx('door');$('room-label').textContent=r.name;updateHUD();}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-120,120),vy:rand(-130,100),life:rand(.2,.6),color,size:rand(2,6)});}
function updateHUD(){if(!player)return;$('health').innerHTML=Array.from({length:player.max},(_,i)=>`<span class="${i>=player.hp?'lost':''}">♥</span>`).join('');$('money').textContent=String(player.money).padStart(2,'0');$('keys').textContent=player.key;$('damage').textContent=`${player.damage} dégât${player.damage>1?'s':''} · ${player.fire?'lame ardente':'courage illimité'}`;$('explored').textContent=`${rooms.filter(r=>r.visited).length} / 12`;$('relic-count').textContent=player.items.length;$('room-status').textContent=room.clear?'ZONE SÛRE':'COMBAT EN COURS';$('room-status').style.color=room.clear?'#c8e98b':'#eb9b7c';$('relics').innerHTML=player.items.length?player.items.map(r=>`<div class="relic"><span>${r.icon}</span><div>${r.name}<small>${r.desc}</small></div></div>`).join(''):'<p class="empty">Les grandes légendes<br>commencent les mains vides.</p>';drawMap();}
function drawMap(){mc.clearRect(0,0,260,155);for(const r of rooms){const visible=r.visited||rooms.some(v=>v.visited&&Math.abs(v.x-r.x)+Math.abs(v.y-r.y)===1);if(!visible)continue;const x=114+r.x*43,y=124+r.y*34;for(const n of rooms.filter(n=>n.visited&&Math.abs(n.x-r.x)+Math.abs(n.y-r.y)===1)){mc.fillStyle='#394b36';mc.fillRect(Math.min(x,114+n.x*43)+13,Math.min(y,124+n.y*34)+9,Math.abs(n.x-r.x)*43+2,Math.abs(n.y-r.y)*34+2);}mc.fillStyle=r===room?'#bedf87':r.visited?'#3a5140':'#23342a';mc.fillRect(x,y,28,20);mc.strokeStyle=r===room?'#effbc7':'#526346';mc.strokeRect(x+.5,y+.5,27,19);if(r.visited||r.type==='boss'){mc.fillStyle=r===room?'#263d24':r.type==='treasure'||r.type==='key'?'#dfbe6f':r.type==='boss'?'#dd8e76':'#a3b69a';mc.font='12px monospace';mc.textAlign='center';mc.fillText(({treasure:'◆',shop:'$',boss:'☠',key:'⚿',start:'·',ante:'+'})[r.type]||'·',x+14,y+14);}}}
function blocked(x,y,radius=12){return x<48+radius||x>912-radius||y<64+radius||y>576-radius||room.objects.some(o=>x+radius>o.x&&x-radius<o.x+o.w&&y+radius>o.y&&y-radius<o.y+o.h);}
function move(e,dx,dy,radius=12){if(!blocked(e.x+dx,e.y,radius))e.x+=dx;if(!blocked(e.x,e.y+dy,radius))e.y+=dy;}
function attack(){if(mode!=='play'||player.attackCD>0)return;player.attack=.2;player.attackCD=.32;sfx('sword');for(const e of room.enemies){const a=Math.atan2(e.y-player.y,e.x-player.x),d=Math.atan2(Math.sin(a-player.dir),Math.cos(a-player.dir));if(dist(e,player)<(e.type==='boss'?110:84)&&Math.abs(d)<1.65)hit(e,player.damage,true);}}
function hit(e,d,melee=false){e.hp-=d*(e.type==='boss'&&e.recover>0?2:1);e.hit=.14;if(melee&&player.fire)e.burn=2.5;burst(e.x,e.y,e.type==='boss'?'#dbbf78':'#d5df9c',7);sfx('hit');if(e.type!=='boss'){const a=Math.atan2(e.y-player.y,e.x-player.x);move(e,Math.cos(a)*15,Math.sin(a)*15);}}
function hurt(){if(player.inv>0||player.dash>0)return;player.hp--;player.inv=1.2;shake=9;burst(player.x,player.y,'#ef9c83');sfx('hurt');updateHUD();if(player.hp<=0)end(false);}
function throwBoom(){if(mode!=='play'||boomerang||player.boomCD>0)return;boomerang={x:player.x,y:player.y,vx:Math.cos(player.dir)*410,vy:Math.sin(player.dir)*410,t:0,hit:new Set()};player.boomCD=1.4;sfx('boomerang');}
function interact(){if(mode!=='play'||!room.clear)return;const p=player;if(room.type==='treasure'&&!room.opened&&dist(p,{x:480,y:285})<92){mode='choice';sfx('treasure');$('overlay').innerHTML=`<div class="intro-symbol">◆</div><div class="eyebrow">LA CHAMBRE DES OFFRANDES</div><h2>Choisissez votre relique.</h2><p>Un seul don. Il vous accompagnera jusqu’au bout.</p><div class="choices">${room.offer.map((r,i)=>`<button class="choice" data-choice="${i}"><em>${r.icon}</em><strong>${r.name}</strong><small>${r.desc}</small></button>`).join('')}</div>`;$('overlay').classList.remove('hidden');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{addRelic(room.offer[Number(b.dataset.choice)]);room.opened=true;mode='play';$('overlay').classList.add('hidden');canvas.focus();});}
if(room.type==='shop'){const items=[{x:330,price:8,name:'Potion',run:()=>{if(p.hp===p.max){toast('Vos cœurs sont déjà pleins.');return false;}p.hp=Math.min(p.max,p.hp+3);return true;}},{x:480,price:16,name:'Éclat de puissance',run:()=>{addRelic(relics[0]);return true;}},{x:630,price:14,name:'Cœur de la forêt',run:()=>{addRelic(relics[1]);return true;}}];const item=items.find((v,i)=>!room['sold'+i]&&dist(p,{x:v.x,y:350})<75);if(item){const i=items.indexOf(item);if(p.money<item.price)toast(`Il vous faut ${item.price} rubis.`);else if(item.run()){p.money-=item.price;room['sold'+i]=true;toast('Merci, voyageur. Que la forêt vous protège.');sfx('buy');updateHUD();}}}
if(room.type==='ante'&&!room.opened&&dist(p,{x:480,y:260})<85){p.hp=p.max;room.opened=true;burst(480,260,'#b7e4ac',35);toast('La source vous soigne entièrement.');sfx('heal');updateHUD();}}
function addRelic(r){r.apply(player);player.items.push(r);sfx('relic');toast(`${r.name} — ${r.desc}`);updateHUD();}
function end(win){mode=win?'win':'dead';if(win)legacy.wins++;else legacy.deaths++;persist();keys.clear();$('overlay').innerHTML=`<div class="intro-symbol">${win?'✦':'❧'}</div><div class="eyebrow">${win?'ÉTAGE TERMINÉ':'LA FORÊT GARDE VOTRE ÉCHO'}</div><h2>${win?'La lumière revient.':'Une légende s’achève.'}</h2><p>${win?'Morne-Racine est tombé. Le sanctuaire respire à nouveau.':'Chaque chute ouvre un nouveau chemin.'}<br>${Math.floor(time/60)} min ${Math.floor(time%60)} s · ${kills} ennemis vaincus · ${player.items.length} reliques<br>${legacy.wins} victoire${legacy.wins>1?'s':''} · ${legacy.deaths} chute${legacy.deaths>1?'s':''}</p><button class="primary" id="again">${win?'UNE NOUVELLE AVENTURE':'REPRENDRE L’ÉPÉE'} →</button><small>HÉRITAGE : ${Math.min(8,(legacy.deaths+legacy.wins)*2)} RUBIS AU DÉPART DE LA PROCHAINE TENTATIVE</small>`;$('overlay').classList.remove('hidden');$('again').onclick=newRun;soundtrack.update(false,'');sfx(win?'win':'death');}
function pause(){if(mode==='play'){mode='pause';soundtrack.setPaused(true);keys.clear();$('overlay').innerHTML='<div class="intro-symbol">Ⅱ</div><div class="eyebrow">LE TEMPS SUSPEND SON VOL</div><h2>Un instant de répit.</h2><p>Votre aventure vous attend.</p><button class="primary" id="resume">REPRENDRE →</button>';$('overlay').classList.remove('hidden');$('resume').onclick=pause;}else if(mode==='pause'){mode='play';soundtrack.setPaused(false);soundtrack.unlock();$('overlay').classList.add('hidden');canvas.focus();}}
function projectile(e,a,speed=150){sfx('shot');shots.push({x:e.x,y:e.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:5});}

function updateBoss(e,dt,a){
  const rage=e.hp<e.max*.5;
  if(rage&&e.phase===0)sfx('rage');
  e.phase=rage?1:0;
  if(e.recover>0){e.recover=Math.max(0,e.recover-dt);return;}
  if(e.windup>0){
    e.windup=Math.max(0,e.windup-dt);
    if(e.windup===0){e.charge=.65;e.vx=Math.cos(e.aim)*220;e.vy=Math.sin(e.aim)*220;sfx('charge');}
    return;
  }
  if(e.charge>0){
    e.charge=Math.max(0,e.charge-dt);move(e,e.vx*dt,e.vy*dt,34);
    if(Math.random()<.3)burst(e.x,e.y+30,'#70854b',2);
    if(e.charge===0){e.recover=1.35;e.cool=2.6;burst(e.x,e.y,'#b3c889',18);}
    return;
  }
  move(e,Math.cos(a)*(rage?38:24)*dt,Math.sin(a)*(rage?38:24)*dt,34);
  if(e.cool>0)return;
  const pattern=e.pattern++%3;
  if(pattern===0){
    const count=rage?8:6;
    for(let i=0;i<count;i++)projectile(e,i*TAU/count+a+Math.PI/count,rage?115:100);
    e.cool=rage?2.3:2.8;
  }else if(pattern===1){
    for(let i=-(rage?1:0);i<=(rage?1:0);i++)projectile(e,a+i*.35,135);
    e.cool=2.6;
  }else{
    e.aim=a;e.windup=.95;e.cool=3.8;sfx('warning');
  }
}

function update(dt){if(mode!=='play')return;time+=dt;transition=Math.max(0,transition-dt);for(const k of ['inv','attack','attackCD','dash','dashCD','boomCD'])player[k]=Math.max(0,player[k]-dt);let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('q')||keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('z')||keys.has('w')||keys.has('arrowup')?1:0);if(dx||dy){const n=Math.hypot(dx,dy);dx/=n;dy/=n;if(!player.dash)player.dir=Math.atan2(dy,dx);}if(keys.has('shift')&&player.dashCD<=0&&(dx||dy)){player.dash=.18;player.dashCD=.85;sfx('dash');burst(player.x,player.y,'#b6d5ac',6);}if(player.dash>0){dx=Math.cos(player.dir);dy=Math.sin(player.dir);}move(player,dx*player.speed*dt*(player.dash>0?3.3:1),dy*player.speed*dt*(player.dash>0?3.3:1));if(keys.has(' ')||keys.has('j'))attack();if(keys.has('k'))throwBoom();
if(room.clear&&transition===0){let next,from;if(player.x<76&&Math.abs(player.y-320)<47&&dx<0){next=neighbor(-1,0);from='right';}if(player.x>884&&Math.abs(player.y-320)<47&&dx>0){next=neighbor(1,0);from='left';}if(player.y<93&&Math.abs(player.x-480)<47&&dy<0){next=neighbor(0,-1);from='bottom';}if(player.y>547&&Math.abs(player.x-480)<47&&dy>0){next=neighbor(0,1);from='top';}if(next){if(next.type==='boss'&&!next.visited&&!player.key){toast('La porte réclame la clé de lune. Explorez l’ouest.');transition=1;}else{if(next.type==='boss'&&!next.visited)player.key--;room.drops=drops;enter(next,from);}}}
for(const e of room.enemies){e.t+=dt;e.cool-=dt;e.hit=Math.max(0,e.hit-dt);if(e.burn>0){e.burn-=dt;e.hp-=dt*.8;if(Math.random()<dt*20)burst(e.x,e.y,'#eead55',1);}const a=Math.atan2(player.y-e.y,player.x-e.x),d=dist(player,e);if(e.type==='slime'){if(Math.sin(e.t*3)>-.1)move(e,Math.cos(a)*65*dt,Math.sin(a)*65*dt);}if(e.type==='bat'){move(e,(Math.cos(a)*100+Math.cos(e.t*4)*48)*dt,(Math.sin(a)*100+Math.sin(e.t*3)*48)*dt);}if(e.type==='spitter'){if(d<170)move(e,-Math.cos(a)*45*dt,-Math.sin(a)*45*dt);if(e.cool<=0){projectile(e,a);e.cool=2.2;}}if(e.type==='knight'){if(e.charge>0){e.charge-=dt;move(e,e.vx*dt,e.vy*dt);}else if(e.cool<0){e.charge=.65;e.vx=Math.cos(a)*250;e.vy=Math.sin(a)*250;e.cool=2.2;}else if(e.cool>.6)move(e,Math.cos(a)*45*dt,Math.sin(a)*45*dt);}
if(e.type==='boss')updateBoss(e,dt,a);
if(d<(e.type==='boss'?47:25))hurt();}
if(boomerang){const b=boomerang;b.t+=dt;if(b.t>.48){const a=Math.atan2(player.y-b.y,player.x-b.x);b.vx=Math.cos(a)*480;b.vy=Math.sin(a)*480;if(dist(b,player)<22){boomerang=null;sfx('catch');}}b.x+=b.vx*dt;b.y+=b.vy*dt;for(const e of room.enemies)if(dist(b,e)<(e.type==='boss'?48:25)&&!b.hit.has(e)){b.hit.add(e);hit(e,player.boomDamage);}if(b.t>3)boomerang=null;}
for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(blocked(s.x,s.y,4))s.life=0;if(dist(s,player)<17){hurt();s.life=0;}}shots=shots.filter(s=>s.life>0);
for(const e of room.enemies.filter(e=>e.hp<=0)){kills++;sfx('enemy');burst(e.x,e.y,'#c6d187',22);if(e.type!=='boss'){drops.push({x:e.x,y:e.y,type:'rupee',value:Math.floor(rand(2,5))});if(Math.random()<.16)drops.push({x:e.x+18,y:e.y,type:'heart'});}}room.enemies=room.enemies.filter(e=>e.hp>0);
if(!room.clear&&!room.enemies.length&&mode==='play'){room.clear=true;clears++;player.money+=3;if(player.regen)player.hp=Math.min(player.max,player.hp+1);sfx('clear');if(room.type==='boss'){end(true);}else if(room.type==='key'){drops.push({x:480,y:300,type:'key'});toast('La clé de lune apparaît !');}else toast('Salle purifiée · +3 rubis');updateHUD();}
for(const d of drops){if(dist(d,player)<27&&(d.type!=='heart'||player.hp<player.max)){if(d.type==='rupee')player.money+=d.value;if(d.type==='heart')player.hp=Math.min(player.max,player.hp+1);if(d.type==='key'){player.key++;toast('Clé de lune obtenue. Le gardien vous attend au nord-est.');}d.taken=true;sfx(d.type==='rupee'?'coin':d.type==='heart'?'heal':'key');updateHUD();}}drops=drops.filter(d=>!d.taken);
let hint=room.clear?'Empruntez une porte pour explorer':'Éliminez les ennemis pour ouvrir les portes';if(room.type==='treasure'&&!room.opened)hint='Approchez du coffre et appuyez sur E';if(room.type==='shop')hint='Approchez d’un article · E pour acheter';if(room.type==='ante'&&!room.opened)hint='E près de la source · soin complet';$('hint').textContent=hint;$('timer').textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(Math.floor(time%60)).padStart(2,'0')}`;
}
const palettes={hero:{g:'#6b994c',G:'#adc96d',d:'#2a4834',s:'#edc48f',h:'#a57c43',b:'#805b3c',w:'#e2e5c5'},slime:{a:'#6f9f78',b:'#9ccb99',d:'#294c43',e:'#e8dfad'},bat:{a:'#89719a',b:'#b49aac',d:'#423b59',e:'#f4cba0'},spitter:{a:'#b27752',b:'#d6a16b',d:'#5f4b3c',e:'#f5d9a2'},knight:{a:'#759a99',b:'#b0c1ab',d:'#334951',e:'#e4a574'}};
const sprites={hero:['.....ggg......','....gGGgg.....','...ggGGggg....','...hhhss......','...hssds......','....ssss......','..ddggggdd....','.ddgGGgggdd...','..sgGGgggs....','...gggggg.....','...bbbbb......','...bb.bb......','..bbb.bbb.....'],slime:['....aaaa....','..aabbbbaa..','.abbbbbbbba.','aabbbbbbbbaa','abddbbddbbba','abedbbedbbba','aabbbbbbbbaa','.aaddddddaa.','..aaaaaaaa..'],bat:['a..........a','aa........aa','aba..aa..aba','abbaaaaaabba','abbbabbabbba','.abbdeedbba.','..aabbbbaa..','....aaaa....'],spitter:['....aaaa....','..aabbbbaa..','.abbbbbbbba.','abddbbddbbba','abeebb eebba'.replace(' ',''),'aabddddbbaa.','.aabddbaa...','..aaaaaaa...','.aaa..aaa...'],knight:['....bbbb....','...baaaab...','..bbaaaabb..','..bddddebb..','...dddddd...','.aaaaaaaaaa.','abbaaaaaabba','abbaaaaaabba','.dadaaaadad.','...aaaaaa...','...dd.dd....','..ddd.ddd...']};
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}
function sprite(name,x,y,scale=3,flash=false){const s=sprites[name],p=palettes[name],sw=s[0].length*scale;for(let row=0;row<s.length;row++)for(let col=0;col<s[row].length;col++){const c=p[s[row][col]];if(c)rect(x-sw/2+col*scale,y-s.length*scale+row*scale,scale,scale,flash?'#f6f1cf':c);}}
function text(t,x,y,size=12,color='#dce7bb'){ctx.font=`${size}px monospace`;ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(t,x,y);}
function noise(x,y){let n=Math.sin(x*127.1+y*311.7+room.seed)*43758.5453;return n-Math.floor(n);}
function floor(){rect(0,0,W,H,'#111f1c');for(let y=2;y<18;y++)for(let x=1;x<29;x++){const n=noise(x,y);rect(x*32,y*32,32,32,n>.75?'#29392c':n>.3?'#26362a':'#243329');rect(x*32,y*32,31,1,'#30402e');rect(x*32,y*32,1,31,'#1c2d25');if(n>.76){rect(x*32+8,y*32+9,7,2,'#394931');rect(x*32+21,y*32+25,3,3,'#405034');}if(n<.12){rect(x*32+14,y*32+17,8,1,'#172a23');rect(x*32+21,y*32+18,1,7,'#172a23');}}
for(let y=0;y<20;y++)for(let x=0;x<30;x++)if(y<2||y>=18||x<2||x>=28){const n=noise(x,y);rect(x*32,y*32,31,30,n>.5?'#425444':'#394c40');rect(x*32+2,y*32+2,27,4,'#51634c');rect(x*32+2,y*32+25,28,5,'#20382e');if(n>.6)rect(x*32+3,y*32+6,8,10,'#627445');}
rect(64,64,832,10,'#11271f');rect(64,74,10,502,'#172a22');rect(886,74,10,502,'#172a22');for(const [x,y] of [[88,92],[844,92],[88,518],[844,518]]){rect(x-8,y-8,32,38,'#1a2d25');rect(x-4,y-8,24,28,'#627257');rect(x,y-5,16,3,'#8a9671');rect(x+3,y+3,10,13,'#3b5341');}
for(let i=0;i<36;i++){const x=75+noise(i,50)*810,y=i%2?78+noise(i,40)*35:535+noise(i,45)*30;rect(x,y,3,9,'#536f3b');rect(x-3,y+4,9,3,'#496638');}
for(const [dx,dy,x,y,vertical] of [[-1,0,32,280,true],[1,0,880,280,true],[0,-1,440,32,false],[0,1,440,560,false]]){const n=neighbor(dx,dy);if(!n)continue;rect(x-5,y-5,vertical?58:90,vertical?90:58,'#788469');rect(x,y,vertical?48:80,vertical?80:48,'#15291f');rect(x+4,y+4,vertical?40:72,vertical?72:40,'#0d1b18');const locked=!room.clear||(n.type==='boss'&&!n.visited&&!player.key);if(locked){for(let i=0;i<4;i++)rect(x+(vertical?7:i*19+5),y+(vertical?i*19+5:5),vertical?34:5,vertical?5:34,'#9a9165');if(n.type==='boss')text('◆',x+24,y+31,24,'#d2ae64');}else{rect(x+(vertical?20:30),y+(vertical?30:20),vertical?8:20,vertical?20:8,'#a1b879');} }
for(const [x,y] of [[168,87],[788,87],[168,551],[788,551]]){rect(x-6,y,12,13,'#3b3225');rect(x-8,y-8,16,11,'#b18c46');rect(x-5,y-15-Math.sin(time*9+x)*2,10,13,'#e6b660');rect(x-2,y-15,4,8,'#f5dfa0');const glow=ctx.createRadialGradient(x,y,4,x,y,60);glow.addColorStop(0,'#e8b74b16');glow.addColorStop(1,'#e8b74b00');ctx.fillStyle=glow;ctx.fillRect(x-60,y-60,120,120);}
for(const o of room.objects){rect(o.x-4,o.y+8,o.w+8,o.h,'#15291f');rect(o.x,o.y,o.w,o.h,'#53664e');rect(o.x+4,o.y+4,o.w-8,9,'#7e8b63');rect(o.x+6,o.y+17,o.w-12,23,'#405740');rect(o.x+18,o.y+18,10,17,'#657b51');rect(o.x+2,o.y+34,12,12,'#79914e');}
}
function chest(x,y,opened){rect(x-31,y+8,62,13,'#14251c');rect(x-28,y-17,56,35,'#745634');rect(x-25,y-21,50,17,opened?'#242d22':'#b48c4b');rect(x-25,y-21,50,5,'#d4b563');rect(x-24,y+7,48,5,'#a58448');rect(x-19,y-18,5,35,'#d2b163');rect(x+14,y-18,5,35,'#d2b163');rect(x-5,y-7,10,12,'#e1c876');rect(x-1,y-3,3,6,'#594630');if(!opened){text('✦',x,y-46+Math.sin(time*2)*4,18,'#c9d898');}}
function decorations(){if(room.type==='start'){for(let i=0;i<3;i++)rect(397+i*12,210+i*12,166-i*24,105-i*24,'#384d36');text('✦',480,284,55,'#758957');text('LE SEUIL DU SANCTUAIRE',480,480,12,'#819576');}if(room.type==='treasure')chest(480,285,room.opened);if(room.type==='key'&&!room.clear){rect(440,270,80,50,'#53634b');text('☾',480,303,32,'#c8ba7b');}if(room.type==='ante'){rect(436,221,88,64,'#5d7560');rect(443,228,74,48,room.opened?'#38524a':'#68a29b');rect(453,233,50,4,'#aad7c0');text('SOURCE DES FÉES',480,194,12,'#b2c1a0');if(!room.opened)text('✦',480+Math.sin(time)*24,246+Math.sin(time*2)*6,22,'#ddedac');}
if(room.type==='shop'){sprite('hero',480,235,4);rect(458,184,44,11,'#af8963');rect(445,188,68,8,'#9e714c');text('« Quelques rubis contre un peu d’espoir ? »',480,153,13,'#bcc8a4');for(let i=0;i<3;i++){const x=330+i*150;rect(x-40,328,80,52,'#4f5136');rect(x-44,324,88,8,'#a18a58');if(!room['sold'+i]){text(['♥','⚔','♥'][i],x,311,32,['#d88779','#dce0b8','#eab795'][i]);text(['POTION','PUISSANCE','CŒUR +1'][i],x,406,11);text([8,16,14][i]+' ◆',x,428,14,'#dfc778');}else text('VENDU',x,410,12,'#789077');}}
if(room.type==='boss'){ctx.strokeStyle='#50613b';ctx.lineWidth=4;ctx.beginPath();ctx.arc(480,320,150,0,TAU);ctx.stroke();for(let i=0;i<8;i++){const a=i*TAU/8;text('◆',480+Math.cos(a)*150,327+Math.sin(a)*150,17,'#6b7947');}}
}
function bossSprite(e){const x=e.x,y=e.y;ctx.save();ctx.translate(Math.round(x),Math.round(y));if(e.hit>0)ctx.globalAlpha=.65;for(let i=0;i<5;i++){const rx=-55+i*24;rect(rx,8,16,37,'#554832');rect(rx-8,35,28,10,'#726341');}rect(-39,-47,78,76,'#766447');rect(-47,-33,94,47,'#61573c');rect(-33,-50,66,8,'#a2905a');rect(-48,-69,26,34,'#495e3c');rect(23,-71,29,37,'#53683b');rect(-59,-79,33,18,'#718449');rect(32,-86,32,23,'#7e8d4f');rect(-15,-73,34,29,'#627940');rect(-21,-84,46,17,'#839551');rect(-28,-30,20,14,'#252f23');rect(9,-30,20,14,'#252f23');rect(-23,-26,10,7,e.phase?'#f6a56d':'#e2d486');rect(13,-26,10,7,e.phase?'#f6a56d':'#e2d486');rect(-16,1,34,8,'#2e3727');rect(-5,-9,12,9,'#ac975b');if(e.windup>0||e.charge>0){ctx.strokeStyle='#efb878';ctx.lineWidth=3;ctx.strokeRect(-52,-90,105,135);}ctx.restore();if(e.recover>0)text('VULNÉRABLE ×2',e.x,e.y-100,12,'#c8e98b');}
function draw(){ctx.save();ctx.translate(Math.round(rand(-shake,shake)),Math.round(rand(-shake,shake)));floor();decorations();for(const e of room.enemies)if(e.type==='boss'&&e.windup>0){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.aim);ctx.fillStyle='#ecb26935';ctx.fillRect(0,-32,220*.65,64);ctx.strokeStyle='#f1c078';ctx.lineWidth=3;ctx.setLineDash([10,8]);ctx.strokeRect(0,-32,220*.65,64);ctx.restore();text('CHARGE !',e.x,e.y-103,14,'#f1c078');}for(const d of drops){const y=d.y+Math.sin(time*4)*3;if(d.type==='rupee'){ctx.save();ctx.translate(d.x,y);ctx.rotate(Math.PI/4);rect(-6,-6,12,12,'#85c7a2');rect(-4,-4,4,9,'#d0e7a6');ctx.restore();}else text(d.type==='heart'?'♥':'⚿',d.x,y,25,d.type==='heart'?'#e68f7e':'#e7cf79');}
const actors=[...room.enemies,{...player,type:'player'}].sort((a,b)=>a.y-b.y);for(const e of actors){ctx.fillStyle='#0d211b80';ctx.beginPath();ctx.ellipse(e.x,e.y+12,e.type==='boss'?54:19,e.type==='boss'?16:7,0,0,TAU);ctx.fill();if(e.type==='player'){if(player.inv>0&&Math.floor(time*15)%2===0)ctx.globalAlpha=.45;sprite('hero',e.x,e.y+15,3);ctx.globalAlpha=1;const a=player.dir;ctx.save();ctx.translate(e.x,e.y-1);ctx.rotate(a);if(player.attack>0){ctx.fillStyle='#e5ecc080';ctx.beginPath();ctx.arc(0,0,77,-1.2,1.2);ctx.arc(0,0,47,1.2,-1.2,true);ctx.fill();}ctx.rotate(player.attack>0?(-1.2+(1-player.attack/.2)*2.4):.4);rect(19,-3,player.attack>0?43:23,6,'#dfe3c1');rect(23,-7,4,14,'#b5a265');rect(14,-3,10,6,'#80633c');ctx.restore();if(player.dashCD>0){rect(e.x-16,e.y+24,32,3,'#233c2c');rect(e.x-16,e.y+24,32*(1-player.dashCD/.85),3,'#a9c97a');}}else if(e.type==='boss')bossSprite(e);else{sprite(e.type,e.x,e.y+12+(e.type==='bat'?Math.sin(e.t*12)*5:0),3,e.hit>0);if(e.hp<e.max){rect(e.x-16,e.y-29,32,3,'#23392b');rect(e.x-16,e.y-29,32*e.hp/e.max,3,'#c1c283');}if(e.type==='knight'&&e.cool<.6&&e.charge<=0)text('!',e.x,e.y-39,20,'#e6c080');}}
for(const s of shots){rect(s.x-6,s.y-6,12,12,'#a45e42');rect(s.x-3,s.y-3,6,6,'#efc274');}if(boomerang){ctx.save();ctx.translate(boomerang.x,boomerang.y);ctx.rotate(time*20);rect(-12,-12,24,5,'#edce7a');rect(7,-12,5,24,'#bb8d4f');ctx.restore();}for(const p of particles)rect(p.x,p.y,p.size,p.size,p.color);
for(let i=0;i<16;i++){const x=(i*177+Math.sin(time*.4+i)*60+runSeed)%830+65,y=(i*97+time*(3+i%3))%470+85;ctx.globalAlpha=.25+Math.sin(time*2+i)*.2;rect(x,y,3,3,'#d6e6a2');}ctx.globalAlpha=1;
const vignette=ctx.createRadialGradient(480,320,180,480,320,530);vignette.addColorStop(0,'#06151000');vignette.addColorStop(1,'#061510aa');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);if(room.type==='boss'&&room.enemies.length){const e=room.enemies[0];text('MORNE-RACINE',480,109,14,'#e4d3a6');rect(300,119,360,8,'#242c21');rect(301,120,358*e.hp/e.max,6,e.phase?'#e18d62':'#c4b476');}ctx.restore();}
function frame(t){soundtrack.update(mode==='play',room.type==='boss'&&!room.clear?'boss':room.type==='shop'?'shop':'forest');const dt=Math.min((t-last)/1000,.035);last=t;update(dt);if(mode==='play'){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt*35);if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0;}}draw();requestAnimationFrame(frame);}
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','shift'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='escape')pause();if(k==='e')interact();if(k==='enter'&&mode==='title')newRun();});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(mode==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')pause();});canvas.addEventListener('pointerdown',e=>{canvas.focus();if(mode!=='play')return;const r=canvas.getBoundingClientRect();player.dir=Math.atan2((e.clientY-r.top)*H/r.height-player.y,(e.clientX-r.left)*W/r.width-player.x);attack();});$('start').onclick=newRun;$('pause').onclick=pause;$('sound').onclick=()=>{soundtrack.setEnabled(!soundtrack.enabled);syncSoundButton();if(soundtrack.enabled)sfx('coin');};$('fullscreen').onclick=()=>{const promise=document.fullscreenElement?document.exitFullscreen():$('game-wrap').requestFullscreen();promise?.catch(()=>toast('Le plein écran n’est pas disponible dans ce navigateur.'));};
player={x:480,y:400,hp:5,max:5,money:0,key:0,items:[],damage:1,dir:-Math.PI/2,inv:0,dashCD:0,attack:0};rooms=layout.map(([x,y,type,name],i)=>({x,y,type,name,id:i,visited:i===0,clear:true,seed:42,objects:[],enemies:[]}));room=rooms[0];updateHUD();if(legacy.wins||legacy.deaths)$('legacy').textContent=`Héritage : ${Math.min(8,(legacy.deaths+legacy.wins)*2)} rubis de départ · ${legacy.wins} victoires · ${legacy.deaths} chutes`;requestAnimationFrame(frame);
})();
